apiVersion: v1
kind: Pod
metadata:
  name: west-dummy-logger
  namespace: default
  labels:
    app: dummy-logger
  annotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: "dummy-logger"
    dapr.io/app-port: "80"
    dapr.io/config: "appconfig"
spec:
  containers:
    - name: west-dummy-logger
      image: denniszielke/dummy-logger:latest
      imagePullPolicy: Always
      env: 
        - name: "METRICRESET"
          value: "5"
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
      resources:
        requests:
          memory: "30Mi"
          cpu: "50m"
        limits:
          memory: "100Mi"
          cpu: "100m"